[
    {"name":"CINNAMON TOAST CRUNCH","company":"GENERAL MILLS","description":"WHOLE GRAIN, WHEAT, RICE","price":2.79,"quantity":25},
    {"name":"HONEY NUT CHEERIOS","company":"GENERAL MILLS","description":"GLUTEN FREE, WHOLE GRAIN, OAT","price":2.79,"quantity":25},
    {"name":"REESES PUFFS","company":"GENERAL MILLS","description":"WHOLE GRAIN, CORN, PEANUT BUTTER","price":2.79,"quantity":25},
    {"name":"COCOA PUFFS","company":"GENERAL MILLS","description":"WHOLE GRAIN, CORN, CHOCOLATE","price":2.79,"quantity":25},
    {"name":"TOTAL","company":"GENERAL MILLS","description":"WHOLE GRAIN, WHEAT, FLAKES","price":2.79,"quantity":25},
    {"name":"TRIX","company":"GENERAL MILLS","description":"GLUTEN FREE, WHOLE GRAIN, CORN, FRUIT","price":2.79,"quantity":25},
    {"name":"LUCKY CHARMS","company":"GENERAL MILLS","description":"WHOLE GRAIN, GLUTEN FREE, OAT, FRUITY","price":2.79,"quantity":25},

    {"name":"FRUITY PEBBLES","company":"POST","description":"GLUTEN FREE, FRUITY, RICE","price":2.79,"quantity":25},
    {"name":"HONEY BUNCHES OF OATS","company":"POST","description":"WHOLE GRAIN, CORN, WHEAT, OAT, HONEY, FLAKES","price":2.79,"quantity":25},
    {"name":"COCOA PEBBLES","company":"POST","description":"GLUTEN FREE, RICE, CHOCOLATE","price":2.79,"quantity":25},
    {"name":"RAISIN BRAN","company":"POST","description":"WHOLE GRAIN, WHEAT, FLAKES","price":2.79,"quantity":25},
    {"name":"GREAT GRAINS BLUEBERRY MORNINGS","company":"POST","description":"WHOLE GRAIN, WHEAT, RICE, OAT, FRUITY, FLAKES","price":2.79,"quantity":25},
    {"name":"CHIPS AHOY","company":"POST","description":"WHOLE GRAIN, CORN, OAT, CHOCOLATE","price":2.79,"quantity":25},
    {"name":"SOUR PATCH","company":"POST","description":"WHOLE GRAIN, CORN, WHEAT, OAT, FRUITY","price":2.79,"quantity":25},

    {"name":"SPECIAL K","company":"KELLOGS","description":"RICE, WHEAT, FLAKES","price":2.79,"quantity":25},
    {"name":"FROSTED FLAKES","company":"KELLOGS","description":"CORN, FLAKES","price":2.79,"quantity":25},
    {"name":"POPS","company":"KELLOGS","description":"CORN","price":2.79,"quantity":25},
    {"name":"RICE KRISPIES","company":"KELLOGS","description":"RICE","price":2.79,"quantity":25},
    {"name":"SMART START","company":"KELLOGS","description":"WHOLE GRAIN, RICE, WHEAT, OAT, FLAKES","price":2.79,"quantity":25},
    {"name":"FROSTED MINI WHEATS","company":"KELLOGS","description":"WHOLE GRAIN, WHEAT","price":2.79,"quantity":25},
    {"name":"FRUIT LOOPS","company":"KELLOGS","description":"WHOLE GRAIN, CORN, WHEAT, OAT, FRUITY","price":2.79,"quantity":25},

    {"name":"CINNAMON CRUNCH","company":"CASCADIAN FARM","description":"ORGANIC, WHOLE GRAIN, VEGAN, WHEAT, RICE, OAT, CINNAMON","price":2.79,"quantity":25},
    {"name":"MULTI GRAIN SQUARES","company":"CASCADIAN FARM","description":"ORGANIC, WHOLE GRAIN, WHEAT, CORN","price":2.79,"quantity":25},
    {"name":"HEARTY MORNING FIBER","company":"CASCADIAN FARM","description":"ORGANIC, WHOLE GRAIN, WHEAT, OAT, RICE, FLAKES","price":2.79,"quantity":25},
    {"name":"GRAHAM CRUNCH","company":"CASCADIAN FARM","description":"ORGANIC, VEGAN, WHEAT, RICE, OAT","price":2.79,"quantity":25},
    {"name":"BERRY VANILLA PUFFS","company":"CASCADIAN FARM","description":"ORGANIC, WHOLE GRAIN, CORN, FRUITY","price":2.79,"quantity":25},
    {"name":"DARK CHOCOLATE ALMOND GRANOLA","company":"CASCADIAN FARM","description":"ORGANIC","price":2.79,"quantity":25},
    {"name":"RAISIN BRAN","company":"CASCADIAN FARM","description":"ORGANIC, WHOLE GRAIN, WHEAT, OAT, FLAKES","price":2.79,"quantity":25},

    {"name":"PURPLE ACAI","company":"NATURES PATH","description":"ORGANIC, WHOLE GRAIN, CORN, FRUITY","price":2.79,"quantity":25},
    {"name":"CRUNCHY MAPLE SUNRISE","company":"NATURES PATH","description":"GLUTEN FREE, WHOLE GRAIN, ORGANIC, VEGAN, RICE, CORN, FLAKES","price":2.79,"quantity":25},
    {"name":"HERITAGE FLAKES","company":"NATURES PATH","description":"ORGANIC, WHOLE GRAIN, WHEAT, OAT, HONEY, FLAKES","price":2.79,"quantity":25},
    {"name":"SMART BRAN","company":"NATURES PATH","description":"ORGANIC, VEGAN, WHOLE GRAIN, WHEAT, OAT","price":2.79,"quantity":25},
    {"name":"CRISPY RICE","company":"NATURES PATH","description":"ORGANIC, GLUTEN FREE, RICE","price":2.79,"quantity":25},
    {"name":"KOALA CRISP","company":"NATURES PATH","description":"ORGANIC, GLUTEN FREE, VEGAN, RICE, CHOCOLATE","price":2.79,"quantity":25},
    {"name":"LEAPIN LEMURS","company":"NATURES PATH","description":"ORGANIC, GLUTEN FREE, VEGAN, CHOCOLATE, PEANUT BUTTER","price":2.79,"quantity":25},

    {"name":"KASHI ORGANIC BLUEBERRY","company":"KASHI","description":"ORGANIC, VEGAN, WHOLE GRAIN, OAT, RICE, FRUITY, FLAKES","price":2.79,"quantity":25},
    {"name":"KASHI ORGANIC STRAWBERRY","company":"KASHI","description":"ORGANIC, VEGAN, RICE, WHOLE GRAIN, WHEAT","price":2.79,"quantity":25},
    {"name":"KASHI CINNAMON FRENCH TOAST","company":"KASHI","description":"VEGAN, CORN","price":2.79,"quantity":25},
    {"name":"KASHI ORGANIC HONEY TOASTED OAT","company":"KASHI","description":"ORGANIC, WHOLE GRAIN, OAT, CORN","price":2.79,"quantity":25},
    {"name":"KASHI BERRY SUPER LOOPS","company":"KASHI","description":"ORGANIC, WHOLE GRAIN, CORN, OAT, FRUITY","price":2.79,"quantity":25},
    {"name":"KASHI CHOCOLATE SUPER LOOPS","company":"KASHI","description":"ORGANIC, WHOLE GRAIN, CORN, OAT, CHOCOLATE","price":2.79,"quantity":25},
    {"name":"KASHI AUTUMN WHEAT","company":"KASHI","description":"ORGANIC, WHOLE GRAIN, WHEAT, VEGAN","price":2.79,"quantity":25}   
]